# Site/SEO settings
email: mikeprokofyev@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Michael Prokofyev
title: Turbo Graphics portfolio
description: Portfolio of Michael Prokofyev and Konstantin Dovzik.
url: http://http://turbographics.s3-website.eu-north-1.amazonaws.com/
# twitter_username: thomasvaeth
default_img: /assets/images/seo.jpg
# social:
#   - name: twitter
#     url: https://twitter.com/thomasvaeth
#   - name: instagram
#     url: https://www.instagram.com/thomas.vaeth/
#   - name: linkedin
#     url: https://www.linkedin.com/in/thomasvaeth/
#   - name: github
#     url: https://github.com/samesies
#   - name: codepen
#     url: https://codepen.io/thomasvaeth/

# # Disqus settings
# disqus: test-apkdzgmqhj

# MailChimp settings
# mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
# mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Michael Prokofyev
    bio: Michael Prokofyev is a programmer, game designer and media artist from Saint-Petersburg.

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Digital Portfolio'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
